import javax.swing.*;
import java.awt.*;

public class ColorChooser
{
   private JPanel colorPanel;

   private ColorChooser()
   {

   }

   public static void createFrame()
   {
      JFrame frame = new JFrame();
      frame.setContentPane(new ColorChooser().colorPanel);
      frame.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
      frame.pack();
      frame.setLocationRelativeTo(null);
      frame.setVisible(true);
   }

   {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
      $$$setupUI$$$();
   }

   /**
    * Method generated by IntelliJ IDEA GUI Designer
    * >>> IMPORTANT!! <<<
    * DO NOT edit this method OR call it in your code!
    */
   private void $$$setupUI$$$()
   {
      colorPanel = new JPanel();
      colorPanel.setLayout(new BorderLayout(0, 0));
      final JColorChooser colorChooser1 = new JColorChooser();
      colorPanel.add(colorChooser1, BorderLayout.CENTER);
   }

   /** @noinspection ALL */
   public JComponent $$$getRootComponent$$$() { return colorPanel; }
}
